project:
  type: book
  output-dir: docs

book:
  title: "経済学のためのデータ分析入門 (R編)"
  author: "みやざきけんじ"
  date: "2025-12-02"
  chapters:
    - index.qmd
    - 01_intro.qmd
    - 02_data.qmd
    - 03_desc_stat_1.qmd
    - 04_desc_stat_2.qmd
    - 05_probability.qmd
    - 06_distributions.qmd
    - 07_sampling.qmd
    - 08_estimation.qmd
    - 09_hypothesis_1.qmd
    - 10_hypothesis_2.qmd
    - 11_regression_1.qmd
    - 12_regression_2.qmd

format: 
    html:
      theme: cosmo
      toc: true
      toc-depth: 2
      number-sections: true
      code-fold: false
      df-print: paged
    pdf:
      pdf-engine: lualatex
      documentclass: ltjsarticle
      classoption: lualatex,ja=standard
    docx: default 

execute:
  warning: false
  message: false
knitr:
  opts_chunk:
    comment: "#>"
    collapse: true

